name: Get 3

on:
  workflow_dispatch:
    
  schedule:
    - cron: '10 19 * * *'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install m3u8 requests

    - name: Set up environment variables
      run: |
        echo "FMM=${{ secrets.FMM }}" >> $GITHUB_ENV
        echo "JSON_URL=${{ secrets.JSON_URL }}" >> $GITHUB_ENV
        echo "JK=${{ secrets.JK }}" >> $GITHUB_ENV
        
    - name: Run Python Script
      run: python fmm.py

    - name: Upload txt file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: zb3.txt
        path: ./zb3.txt

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add zb3.txt
        git commit -m "Update zb3" --allow-empty
        git push
