name: Get 3

on:
  push:
    branches:
      - main

jobs:
  convert_ipvt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download M3U file
        run: |
          curl -s -o temp_file.yml https://raw.githubusercontent.com/Rivens7/Livelist/main/.github/workflows/IPTV_Update.yml

      - name: Convert M3U to TXT
        run: |
          echo "央视频道,#genre#" > zb3.txt
          sed -n 's/^#EXTINF:-1 tvg-name="$[^"]*$".*group-title="[^"]*",$.*$/\1,\2/p' temp_file.yml >> zb3.txt
          echo "卫视频道,#genre#" >> zb3.txt
          sed -n 's/^#EXTINF:-1 tvg-name="$[^"]*$".*group-title="[^"]*",$.*$/\1,\2/p' temp_file.yml >> zb3.txt

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: zb3
          path: zb3.txt

      - name: Clean up
        run: |
          rm temp_file.yml
